<?xml version="1.0"?>

<robot name="base" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- patrick_0803 define a base -->
  <xacro:macro name="base" params="parent length radius offset_z mass">
    <!-- joint -->
	  <joint name="base_joint" type="fixed">
			<origin xyz="0 0 ${offset_z}" rpy="0 0 0"/>
			<parent link="${parent}"/>
			<child link="base_link"/>
	  </joint>
	  <!-- link -->
	  <link name="base_link">
			<visual>
				<geometry>
		      <cylinder length="${length}" radius="${radius}"/>
		      <!--<mesh filename="package://dashgo_description/meshes/base.DAE"/> -->
				</geometry>
				<origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
				<xacro:insert_block name="material_light_grey"/>
			</visual>
			<collision name="base_link">
				<geometry>
				  <cylinder length="${length}" radius="${radius}"/>
				</geometry>
				<origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
			</collision>
			<inertial>
				<!-- COM experimentally determined -->
				<origin xyz="-0.01 0 0"/>
				<mass value="${mass}"/>
				<!-- 2.4/2.6 kg for small/big battery pack -->
				<!-- Kobuki's inertia tensor is approximated by a cylinder with homogeneous mass distribution
				       More details: http://en.wikipedia.org/wiki/List_of_moment_of_inertia_tensors
				       m = 2.4 kg; h = 0.09 m; r = 0.175 m
				       ixx = 1/12 * m * (3 * r^2 + h^2)
				       iyy = 1/12 * m * (3 * r^2 + h^2)
				       izz = 1/2 * m * r^2
				    -->
				<inertia ixx="${mass/12*(3*radius*radius+length*length)}" ixy="0.0" ixz="0.0" 
				         iyy="${mass/12*(3*radius*radius+length*length)}" iyz="0.0" 
				         izz="${mass/2*radius*radius}"/>
			</inertial>
	  </link>
	  
	  <!-- gazebo parameters -->
	  <gazebo reference="base_link">
	    <material>Gazebo/Black</material>
	  </gazebo>
  </xacro:macro>
</robot>
